title: My GitHub Pages Site
author: Your Name
description: A simple website using GitHub Pages and Jekyll

# URL settings
url: "https://ldnbtc.github.io" # Replace with your actual GitHub Pages URL
baseurl: "" # Leave empty if your site is at the root of your domain

# Build settings
markdown: kramdown

# Specify the directory where Jekyll will read files
source: .

# Specify the directory where Jekyll will write files
destination: ./_site

# Set permalink structure for blog posts
permalink: /blog/:year/:month/:day/:title/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
